### ISSUE TITLE
Number Guesses - does not print  "type a number larger than 0"

### ISSUE THREAD

**Issue by pritchardcm** [techwithtim/5-Python-Projects-For-Beginners#26]
when I type a number that is < 0,

it prints "please choose a number next time" 

instead of

"please choose a number larger than zero"

**Comment by Adamsbag** [comment]
Removes a leading minus sign (for negative numbers) by using the method "_**.lstrip**_". Your code should look like this;

if top_of_range**.lstrip('-'**).isdigit():
    top_of_range = int(top_of_range)

Let me know how it goes...

**Comment by pritchardcm** [comment]
This solved the issue! Thank you
